<?php

namespace Vulcan\Seo\Extensions;

use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataExtension;

/**
 * Class MemberExtension
 * @package Vulcan\Seo\Extensions
 *
 * @property string TwitterAccountName
 */
class MemberExtension extends DataExtension
{
    private static $db = [
        'TwitterAccountName' => 'Varchar(80)'
    ];

    /**
     * @param FieldList $fields
     */
    public function updateCMSFields(FieldList $fields)
    {
        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub

        $fields->addFieldsToTab('Root.Main', [
            TextField::create('TwitterAccountName')
        ], 'Password');
    }
}
