<?php

namespace Vulcan\Seo\Extensions;

use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataExtension;

/**
 * Class SiteConfigSettingsExtension
 * @package Vulcan\Seo\Extensions
 *
 * @property string TwitterAccountName
 */
class SiteConfigSettingsExtension extends DataExtension
{
    private static $db = [
        'TwitterAccountName' => 'Varchar(80)'
    ];

    public function updateCMSFields(FieldList $fields)
    {
        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub

        $fields->addFieldsToTab('Root.VulcanSEO', [
            TextField::create('TwitterAccountName')
        ]);
    }
}
